project:
  type: website
  render:
    - index.qmd
website:
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "Pollution en Occitanie"
  site-url: https://arthur-tena.github.io/projet_pollution_occitanie/
  repo-url: https://github.com/arthur-tena/projet_pollution_occitanie
  repo-actions: [source]
  navbar:
    title: "Pollution en Occitanie"
    background: primary
    search: true
    tools:
      - icon: github
        href: https://github.com/arthur-tena/projet_pollution_occitanie
        text: GitHub
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true